# Default values for jupyterhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

iam:
    endpoint: https://iam.cloud.infn.it

hub:
    host: localhost
    port: 30888
    image: dodasts/jupyter-hub:v3.0.1

s3:
    endpoint: https://minio.cloud.infn.it/minio
    bucket: mybucket
